USE WEBTOOLS;

CREATE TABLE `VERSIONLOG` (
  `VERSION_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `SCRIPT` varchar(255) NOT NULL,
  `INSTALLDATE` datetime NOT NULL,
  PRIMARY KEY (`VERSION_ID`)
) ENGINE=InnoDB;
