--
-- Create schema donatenow
--

CREATE DATABASE IF NOT EXISTS DONATENOW;
USE DONATENOW;

DROP TABLE IF EXISTS PLACEMENTS;
CREATE TABLE  `PLACEMENTS` (
  `PLACEMENT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `WIDGET_ID` bigint(20) NOT NULL,
  `PLACEMENT_URL` varchar(2048) NOT NULL,
  `ERROR_COUNT` bigint(20) NOT NULL,
  `VIEW_COUNT` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`PLACEMENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS WIDGET;
CREATE TABLE  `WIDGET` (
  `WIDGET_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `WIDGET_GUID` varchar(128) NOT NULL,
  `WIDGET_USERNAME` varchar(64) NOT NULL,
  `WIDGET_PASSWORD` varchar(64) NOT NULL,
  `WIDGET_ERROR_COUNT` bigint(20) NOT NULL,
  `WIDGET_CREATE_DATE` datetime NOT NULL,
  `WIDGET_HTML` varchar(4096) NOT NULL,
  `WIDGET_VIEW_COUNT` bigint(20) NOT NULL DEFAULT '0',
  `WIDGET_TYPE` varchar(32) NOT NULL,
  PRIMARY KEY (`WIDGET_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS LOGIN_WIDGET;
CREATE TABLE `LOGIN_WIDGET` (
       `LOGIN_WIDGET_ID` bigint(20) NOT NULL auto_increment,
       `LOGIN_WIDGET_LAST_LOGIN_DATE` datetime default NULL,
         PRIMARY KEY (`LOGIN_WIDGET_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CUSTOM_ENTITY_WIDGET;
CREATE TABLE `CUSTOM_ENTITY_WIDGET` (
       `CUSTOM_ENTITY_WIDGET_ID` bigint(20) NOT NULL auto_increment,
       `CUSTOM_ENTITY_NAME`  varchar(255) NOT NULL,
       PRIMARY KEY (`CUSTOM_ENTITY_WIDGET_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS DONATION_WIDGET;
CREATE TABLE `DONATION_WIDGET` (
       `DONATION_WIDGET_ID` bigint(20) NOT NULL auto_increment,
       `DONATION_WINDOW_MOTIVATION_CODE` varchar(64) NOT NULL,
       `DONATION_WIDGET_PROJECT_CODE` varchar(64) NOT NULL,
       PRIMARY KEY (`DONATION_WIDGET_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;

CREATE TABLE `STYLES` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `STYLE` longtext NOT NULL,
  `STYLE_NAME` varchar(128) NOT NULL,
  `USER_NAME` varchar(128) NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `IDX_USER_NAME` (`USER_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
