package com.orangeleap.donatenow.dao;

import com.orangeleap.donatenow.domain.CustomEntityWidget;
import com.orangeleap.donatenow.domain.CustomEntityWidgetExample;
import java.util.List;

public interface CustomEntityWidgetDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int countCustomEntityWidgetByExample(CustomEntityWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int deleteCustomEntityWidgetByExample(CustomEntityWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int deleteCustomEntityWidgetByPrimaryKey(Long customEntityWidgetId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    void insertCustomEntityWidget(CustomEntityWidget record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    void insertCustomEntityWidgetSelective(CustomEntityWidget record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    List<CustomEntityWidget> selectCustomEntityWidgetByExample(CustomEntityWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    CustomEntityWidget selectCustomEntityWidgetByPrimaryKey(Long customEntityWidgetId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updateCustomEntityWidgetByExampleSelective(CustomEntityWidget record, CustomEntityWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updateCustomEntityWidgetByExample(CustomEntityWidget record, CustomEntityWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updateCustomEntityWidgetByPrimaryKeySelective(CustomEntityWidget record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updateCustomEntityWidgetByPrimaryKey(CustomEntityWidget record);
}