package com.orangeleap.donatenow.dao;

import com.orangeleap.donatenow.domain.DonationWidget;
import com.orangeleap.donatenow.domain.DonationWidgetExample;
import java.util.List;

public interface DonationWidgetDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int countDonationWidgetByExample(DonationWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int deleteDonationWidgetByExample(DonationWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int deleteDonationWidgetByPrimaryKey(Long donationWidgetId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    void insertDonationWidget(DonationWidget record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    void insertDonationWidgetSelective(DonationWidget record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    List<DonationWidget> selectDonationWidgetByExample(DonationWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    DonationWidget selectDonationWidgetByPrimaryKey(Long donationWidgetId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updateDonationWidgetByExampleSelective(DonationWidget record, DonationWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updateDonationWidgetByExample(DonationWidget record, DonationWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updateDonationWidgetByPrimaryKeySelective(DonationWidget record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updateDonationWidgetByPrimaryKey(DonationWidget record);
}