package com.orangeleap.donatenow.dao;

import com.orangeleap.donatenow.domain.Widget;
import com.orangeleap.donatenow.domain.WidgetExample;
import java.util.List;

public interface WidgetDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WIDGET
     *
     * @ibatorgenerated Tue Jul 27 17:41:07 CDT 2010
     */
    int countWidgetByExample(WidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WIDGET
     *
     * @ibatorgenerated Tue Jul 27 17:41:07 CDT 2010
     */
    int deleteWidgetByExample(WidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WIDGET
     *
     * @ibatorgenerated Tue Jul 27 17:41:07 CDT 2010
     */
    int deleteWidgetByPrimaryKey(Long widgetId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WIDGET
     *
     * @ibatorgenerated Tue Jul 27 17:41:07 CDT 2010
     */
    void insertWidget(Widget record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WIDGET
     *
     * @ibatorgenerated Tue Jul 27 17:41:07 CDT 2010
     */
    void insertWidgetSelective(Widget record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WIDGET
     *
     * @ibatorgenerated Tue Jul 27 17:41:07 CDT 2010
     */
    List<Widget> selectWidgetByExample(WidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WIDGET
     *
     * @ibatorgenerated Tue Jul 27 17:41:07 CDT 2010
     */
    Widget selectWidgetByPrimaryKey(Long widgetId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WIDGET
     *
     * @ibatorgenerated Tue Jul 27 17:41:07 CDT 2010
     */
    int updateWidgetByExampleSelective(Widget record, WidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WIDGET
     *
     * @ibatorgenerated Tue Jul 27 17:41:07 CDT 2010
     */
    int updateWidgetByExample(Widget record, WidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WIDGET
     *
     * @ibatorgenerated Tue Jul 27 17:41:07 CDT 2010
     */
    int updateWidgetByPrimaryKeySelective(Widget record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WIDGET
     *
     * @ibatorgenerated Tue Jul 27 17:41:07 CDT 2010
     */
    int updateWidgetByPrimaryKey(Widget record);
}