
package com.orangeleap.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.3
 * Tue Jan 19 13:12:03 CST 2010
 * Generated source version: 2.2.3
 * 
 */

public final class OrangeLeap_OrangeLeapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.orangeleap.com/orangeleap/services2.0/", "OrangeLeapService");

    private OrangeLeap_OrangeLeapPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = OrangeLeapService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OrangeLeapService ss = new OrangeLeapService(wsdlURL, SERVICE_NAME);
        OrangeLeap port = ss.getOrangeLeapPort();  
        
        {
        System.out.println("Invoking bulkAddCommunicationHistory...");
        com.orangeleap.client.BulkAddCommunicationHistoryRequest _bulkAddCommunicationHistory_bulkAddCommunicationHistoryRequest = null;
        port.bulkAddCommunicationHistory(_bulkAddCommunicationHistory_bulkAddCommunicationHistoryRequest);


        }
        {
        System.out.println("Invoking getConstituentGift...");
        com.orangeleap.client.GetConstituentGiftRequest _getConstituentGift_getConstituentGiftRequest = null;
        com.orangeleap.client.GetConstituentGiftResponse _getConstituentGift__return = port.getConstituentGift(_getConstituentGift_getConstituentGiftRequest);
        System.out.println("getConstituentGift.result=" + _getConstituentGift__return);


        }
        {
        System.out.println("Invoking findConstituents...");
        com.orangeleap.client.FindConstituentsRequest _findConstituents_findConstituentsRequest = null;
        com.orangeleap.client.FindConstituentsResponse _findConstituents__return = port.findConstituents(_findConstituents_findConstituentsRequest);
        System.out.println("findConstituents.result=" + _findConstituents__return);


        }
        {
        System.out.println("Invoking saveOrUpdateGift...");
        com.orangeleap.client.SaveOrUpdateGiftRequest _saveOrUpdateGift_saveOrUpdateGiftRequest = null;
        com.orangeleap.client.SaveOrUpdateGiftResponse _saveOrUpdateGift__return = port.saveOrUpdateGift(_saveOrUpdateGift_saveOrUpdateGiftRequest);
        System.out.println("saveOrUpdateGift.result=" + _saveOrUpdateGift__return);


        }
        {
        System.out.println("Invoking addCommunicationHistory...");
        com.orangeleap.client.AddCommunicationHistoryRequest _addCommunicationHistory_addCommunicationHistoryRequest = null;
        port.addCommunicationHistory(_addCommunicationHistory_addCommunicationHistoryRequest);


        }
        {
        System.out.println("Invoking getSegmentationById...");
        com.orangeleap.client.GetSegmentationByIdRequest _getSegmentationById_getSegmentationByIdRequest = null;
        com.orangeleap.client.GetSegmentationByIdResponse _getSegmentationById__return = port.getSegmentationById(_getSegmentationById_getSegmentationByIdRequest);
        System.out.println("getSegmentationById.result=" + _getSegmentationById__return);


        }
        {
        System.out.println("Invoking getPickListByName...");
        com.orangeleap.client.GetPickListByNameRequest _getPickListByName_getPickListByNameRequest = null;
        com.orangeleap.client.GetPickListByNameResponse _getPickListByName__return = port.getPickListByName(_getPickListByName_getPickListByNameRequest);
        System.out.println("getPickListByName.result=" + _getPickListByName__return);


        }
        {
        System.out.println("Invoking saveOrUpdateConstituent...");
        com.orangeleap.client.SaveOrUpdateConstituentRequest _saveOrUpdateConstituent_saveOrUpdateConstituentRequest = null;
        com.orangeleap.client.SaveOrUpdateConstituentResponse _saveOrUpdateConstituent__return = port.saveOrUpdateConstituent(_saveOrUpdateConstituent_saveOrUpdateConstituentRequest);
        System.out.println("saveOrUpdateConstituent.result=" + _saveOrUpdateConstituent__return);


        }
        {
        System.out.println("Invoking getPickLists...");
        com.orangeleap.client.GetPickListsRequest _getPickLists_getPickListsRequest = null;
        com.orangeleap.client.GetPickListsResponse _getPickLists__return = port.getPickLists(_getPickLists_getPickListsRequest);
        System.out.println("getPickLists.result=" + _getPickLists__return);


        }
        {
        System.out.println("Invoking getCommunicationHistory...");
        com.orangeleap.client.GetCommunicationHistoryRequest _getCommunicationHistory_getCommunicationHistoryRequest = null;
        com.orangeleap.client.GetCommunicationHistoryResponse _getCommunicationHistory__return = port.getCommunicationHistory(_getCommunicationHistory_getCommunicationHistoryRequest);
        System.out.println("getCommunicationHistory.result=" + _getCommunicationHistory__return);


        }
        {
        System.out.println("Invoking searchConstituents...");
        com.orangeleap.client.SearchConstituentsRequest _searchConstituents_searchConstituentsRequest = null;
        com.orangeleap.client.SearchConstituentsResponse _searchConstituents__return = port.searchConstituents(_searchConstituents_searchConstituentsRequest);
        System.out.println("searchConstituents.result=" + _searchConstituents__return);


        }
        {
        System.out.println("Invoking createDefaultConstituent...");
        com.orangeleap.client.CreateDefaultConstituentRequest _createDefaultConstituent_createDefaultConstituentRequest = null;
        com.orangeleap.client.CreateDefaultConstituentResponse _createDefaultConstituent__return = port.createDefaultConstituent(_createDefaultConstituent_createDefaultConstituentRequest);
        System.out.println("createDefaultConstituent.result=" + _createDefaultConstituent__return);


        }
        {
        System.out.println("Invoking getSegmentationByName...");
        com.orangeleap.client.GetSegmentationByNameRequest _getSegmentationByName_getSegmentationByNameRequest = null;
        com.orangeleap.client.GetSegmentationByNameResponse _getSegmentationByName__return = port.getSegmentationByName(_getSegmentationByName_getSegmentationByNameRequest);
        System.out.println("getSegmentationByName.result=" + _getSegmentationByName__return);


        }
        {
        System.out.println("Invoking getConstituentPledge...");
        com.orangeleap.client.GetConstituentPledgeRequest _getConstituentPledge_getConstituentPledgeRequest = null;
        com.orangeleap.client.GetConstituentPledgeResponse _getConstituentPledge__return = port.getConstituentPledge(_getConstituentPledge_getConstituentPledgeRequest);
        System.out.println("getConstituentPledge.result=" + _getConstituentPledge__return);


        }
        {
        System.out.println("Invoking getSegmentationList...");
        com.orangeleap.client.GetSegmentationListRequest _getSegmentationList_getSegmentationListRequest = null;
        com.orangeleap.client.GetSegmentationListResponse _getSegmentationList__return = port.getSegmentationList(_getSegmentationList_getSegmentationListRequest);
        System.out.println("getSegmentationList.result=" + _getSegmentationList__return);


        }
        {
        System.out.println("Invoking saveOrUpdatePledge...");
        com.orangeleap.client.SaveOrUpdatePledgeRequest _saveOrUpdatePledge_saveOrUpdatePledgeRequest = null;
        com.orangeleap.client.SaveOrUpdatePledgeResponse _saveOrUpdatePledge__return = port.saveOrUpdatePledge(_saveOrUpdatePledge_saveOrUpdatePledgeRequest);
        System.out.println("saveOrUpdatePledge.result=" + _saveOrUpdatePledge__return);


        }
        {
        System.out.println("Invoking getConstituentById...");
        com.orangeleap.client.GetConstituentByIdRequest _getConstituentById_getConstituentByIdRequest = null;
        com.orangeleap.client.GetConstituentByIdResponse _getConstituentById__return = port.getConstituentById(_getConstituentById_getConstituentByIdRequest);
        System.out.println("getConstituentById.result=" + _getConstituentById__return);


        }
        {
        System.out.println("Invoking getSegmentationListByType...");
        com.orangeleap.client.GetSegmentationListByTypeRequest _getSegmentationListByType_getSegmentationListByTypeRequest = null;
        com.orangeleap.client.GetSegmentationListByTypeResponse _getSegmentationListByType__return = port.getSegmentationListByType(_getSegmentationListByType_getSegmentationListByTypeRequest);
        System.out.println("getSegmentationListByType.result=" + _getSegmentationListByType__return);


        }

        System.exit(0);
    }

}
