package com.orangeleap.donatenow.domain;

import java.io.Serializable;
import java.util.Date;

public class LoginWidget implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LOGIN_WIDGET.LOGIN_WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private Long loginWidgetId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LOGIN_WIDGET.LOGIN_WIDGET_LAST_LOGIN_DATE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private Date loginWidgetLastLoginDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LOGIN_WIDGET.LOGIN_WIDGET_ID
     *
     * @return the value of LOGIN_WIDGET.LOGIN_WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Long getLoginWidgetId() {
        return loginWidgetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LOGIN_WIDGET.LOGIN_WIDGET_ID
     *
     * @param loginWidgetId the value for LOGIN_WIDGET.LOGIN_WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setLoginWidgetId(Long loginWidgetId) {
        this.loginWidgetId = loginWidgetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LOGIN_WIDGET.LOGIN_WIDGET_LAST_LOGIN_DATE
     *
     * @return the value of LOGIN_WIDGET.LOGIN_WIDGET_LAST_LOGIN_DATE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Date getLoginWidgetLastLoginDate() {
        return loginWidgetLastLoginDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LOGIN_WIDGET.LOGIN_WIDGET_LAST_LOGIN_DATE
     *
     * @param loginWidgetLastLoginDate the value for LOGIN_WIDGET.LOGIN_WIDGET_LAST_LOGIN_DATE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setLoginWidgetLastLoginDate(Date loginWidgetLastLoginDate) {
        this.loginWidgetLastLoginDate = loginWidgetLastLoginDate;
    }
}