package com.orangeleap.donatenow.dao;

import com.orangeleap.donatenow.domain.LoginWidget;
import com.orangeleap.donatenow.domain.LoginWidgetExample;
import java.util.List;

public interface LoginWidgetDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int countLoginWidgetByExample(LoginWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int deleteLoginWidgetByExample(LoginWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int deleteLoginWidgetByPrimaryKey(Long loginWidgetId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    void insertLoginWidget(LoginWidget record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    void insertLoginWidgetSelective(LoginWidget record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    List<LoginWidget> selectLoginWidgetByExample(LoginWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    LoginWidget selectLoginWidgetByPrimaryKey(Long loginWidgetId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updateLoginWidgetByExampleSelective(LoginWidget record, LoginWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updateLoginWidgetByExample(LoginWidget record, LoginWidgetExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updateLoginWidgetByPrimaryKeySelective(LoginWidget record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updateLoginWidgetByPrimaryKey(LoginWidget record);
}