package com.orangeleap.donatenow.dao;

import com.orangeleap.donatenow.domain.Placements;
import com.orangeleap.donatenow.domain.PlacementsExample;
import java.util.List;

public interface PlacementsDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int countPlacementsByExample(PlacementsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int deletePlacementsByExample(PlacementsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int deletePlacementsByPrimaryKey(Long placementId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    void insertPlacements(Placements record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    void insertPlacementsSelective(Placements record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    List<Placements> selectPlacementsByExample(PlacementsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    Placements selectPlacementsByPrimaryKey(Long placementId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updatePlacementsByExampleSelective(Placements record, PlacementsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updatePlacementsByExample(Placements record, PlacementsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updatePlacementsByPrimaryKeySelective(Placements record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    int updatePlacementsByPrimaryKey(Placements record);
}