package com.orangeleap.donatenow.dao.impl;

import com.orangeleap.donatenow.dao.DonationWidgetDAO;
import com.orangeleap.donatenow.domain.DonationWidget;
import com.orangeleap.donatenow.domain.DonationWidgetExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DonationWidgetDAOImpl extends SqlMapClientDaoSupport implements DonationWidgetDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public DonationWidgetDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int countDonationWidgetByExample(DonationWidgetExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("DONATION_WIDGET.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int deleteDonationWidgetByExample(DonationWidgetExample example) {
        int rows = getSqlMapClientTemplate().delete("DONATION_WIDGET.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int deleteDonationWidgetByPrimaryKey(Long donationWidgetId) {
        DonationWidget key = new DonationWidget();
        key.setDonationWidgetId(donationWidgetId);
        int rows = getSqlMapClientTemplate().delete("DONATION_WIDGET.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void insertDonationWidget(DonationWidget record) {
        getSqlMapClientTemplate().insert("DONATION_WIDGET.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void insertDonationWidgetSelective(DonationWidget record) {
        getSqlMapClientTemplate().insert("DONATION_WIDGET.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    @SuppressWarnings("unchecked")
    public List<DonationWidget> selectDonationWidgetByExample(DonationWidgetExample example) {
        List<DonationWidget> list = getSqlMapClientTemplate().queryForList("DONATION_WIDGET.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public DonationWidget selectDonationWidgetByPrimaryKey(Long donationWidgetId) {
        DonationWidget key = new DonationWidget();
        key.setDonationWidgetId(donationWidgetId);
        DonationWidget record = (DonationWidget) getSqlMapClientTemplate().queryForObject("DONATION_WIDGET.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updateDonationWidgetByExampleSelective(DonationWidget record, DonationWidgetExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("DONATION_WIDGET.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updateDonationWidgetByExample(DonationWidget record, DonationWidgetExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("DONATION_WIDGET.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updateDonationWidgetByPrimaryKeySelective(DonationWidget record) {
        int rows = getSqlMapClientTemplate().update("DONATION_WIDGET.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updateDonationWidgetByPrimaryKey(DonationWidget record) {
        int rows = getSqlMapClientTemplate().update("DONATION_WIDGET.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private static class UpdateByExampleParms extends DonationWidgetExample {
        private Object record;

        public UpdateByExampleParms(Object record, DonationWidgetExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}