package com.orangeleap.donatenow.dao.impl;

import com.orangeleap.donatenow.dao.CustomEntityWidgetDAO;
import com.orangeleap.donatenow.domain.CustomEntityWidget;
import com.orangeleap.donatenow.domain.CustomEntityWidgetExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CustomEntityWidgetDAOImpl extends SqlMapClientDaoSupport implements CustomEntityWidgetDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public CustomEntityWidgetDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int countCustomEntityWidgetByExample(CustomEntityWidgetExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("CUSTOM_ENTITY_WIDGET.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int deleteCustomEntityWidgetByExample(CustomEntityWidgetExample example) {
        int rows = getSqlMapClientTemplate().delete("CUSTOM_ENTITY_WIDGET.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int deleteCustomEntityWidgetByPrimaryKey(Long customEntityWidgetId) {
        CustomEntityWidget key = new CustomEntityWidget();
        key.setCustomEntityWidgetId(customEntityWidgetId);
        int rows = getSqlMapClientTemplate().delete("CUSTOM_ENTITY_WIDGET.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void insertCustomEntityWidget(CustomEntityWidget record) {
        getSqlMapClientTemplate().insert("CUSTOM_ENTITY_WIDGET.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void insertCustomEntityWidgetSelective(CustomEntityWidget record) {
        getSqlMapClientTemplate().insert("CUSTOM_ENTITY_WIDGET.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    @SuppressWarnings("unchecked")
    public List<CustomEntityWidget> selectCustomEntityWidgetByExample(CustomEntityWidgetExample example) {
        List<CustomEntityWidget> list = getSqlMapClientTemplate().queryForList("CUSTOM_ENTITY_WIDGET.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public CustomEntityWidget selectCustomEntityWidgetByPrimaryKey(Long customEntityWidgetId) {
        CustomEntityWidget key = new CustomEntityWidget();
        key.setCustomEntityWidgetId(customEntityWidgetId);
        CustomEntityWidget record = (CustomEntityWidget) getSqlMapClientTemplate().queryForObject("CUSTOM_ENTITY_WIDGET.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updateCustomEntityWidgetByExampleSelective(CustomEntityWidget record, CustomEntityWidgetExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("CUSTOM_ENTITY_WIDGET.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updateCustomEntityWidgetByExample(CustomEntityWidget record, CustomEntityWidgetExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("CUSTOM_ENTITY_WIDGET.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updateCustomEntityWidgetByPrimaryKeySelective(CustomEntityWidget record) {
        int rows = getSqlMapClientTemplate().update("CUSTOM_ENTITY_WIDGET.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updateCustomEntityWidgetByPrimaryKey(CustomEntityWidget record) {
        int rows = getSqlMapClientTemplate().update("CUSTOM_ENTITY_WIDGET.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private static class UpdateByExampleParms extends CustomEntityWidgetExample {
        private Object record;

        public UpdateByExampleParms(Object record, CustomEntityWidgetExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}