package com.orangeleap.donatenow.dao.impl;

import com.orangeleap.donatenow.dao.LoginWidgetDAO;
import com.orangeleap.donatenow.domain.LoginWidget;
import com.orangeleap.donatenow.domain.LoginWidgetExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class LoginWidgetDAOImpl extends SqlMapClientDaoSupport implements LoginWidgetDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public LoginWidgetDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int countLoginWidgetByExample(LoginWidgetExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("LOGIN_WIDGET.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int deleteLoginWidgetByExample(LoginWidgetExample example) {
        int rows = getSqlMapClientTemplate().delete("LOGIN_WIDGET.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int deleteLoginWidgetByPrimaryKey(Long loginWidgetId) {
        LoginWidget key = new LoginWidget();
        key.setLoginWidgetId(loginWidgetId);
        int rows = getSqlMapClientTemplate().delete("LOGIN_WIDGET.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void insertLoginWidget(LoginWidget record) {
        getSqlMapClientTemplate().insert("LOGIN_WIDGET.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void insertLoginWidgetSelective(LoginWidget record) {
        getSqlMapClientTemplate().insert("LOGIN_WIDGET.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    @SuppressWarnings("unchecked")
    public List<LoginWidget> selectLoginWidgetByExample(LoginWidgetExample example) {
        List<LoginWidget> list = getSqlMapClientTemplate().queryForList("LOGIN_WIDGET.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public LoginWidget selectLoginWidgetByPrimaryKey(Long loginWidgetId) {
        LoginWidget key = new LoginWidget();
        key.setLoginWidgetId(loginWidgetId);
        LoginWidget record = (LoginWidget) getSqlMapClientTemplate().queryForObject("LOGIN_WIDGET.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updateLoginWidgetByExampleSelective(LoginWidget record, LoginWidgetExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("LOGIN_WIDGET.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updateLoginWidgetByExample(LoginWidget record, LoginWidgetExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("LOGIN_WIDGET.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updateLoginWidgetByPrimaryKeySelective(LoginWidget record) {
        int rows = getSqlMapClientTemplate().update("LOGIN_WIDGET.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updateLoginWidgetByPrimaryKey(LoginWidget record) {
        int rows = getSqlMapClientTemplate().update("LOGIN_WIDGET.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private static class UpdateByExampleParms extends LoginWidgetExample {
        private Object record;

        public UpdateByExampleParms(Object record, LoginWidgetExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}