package com.orangeleap.donatenow.dao.impl;

import com.orangeleap.donatenow.dao.PlacementsDAO;
import com.orangeleap.donatenow.domain.Placements;
import com.orangeleap.donatenow.domain.PlacementsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PlacementsDAOImpl extends SqlMapClientDaoSupport implements PlacementsDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public PlacementsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int countPlacementsByExample(PlacementsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("PLACEMENTS.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int deletePlacementsByExample(PlacementsExample example) {
        int rows = getSqlMapClientTemplate().delete("PLACEMENTS.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int deletePlacementsByPrimaryKey(Long placementId) {
        Placements key = new Placements();
        key.setPlacementId(placementId);
        int rows = getSqlMapClientTemplate().delete("PLACEMENTS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void insertPlacements(Placements record) {
        getSqlMapClientTemplate().insert("PLACEMENTS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void insertPlacementsSelective(Placements record) {
        getSqlMapClientTemplate().insert("PLACEMENTS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    @SuppressWarnings("unchecked")
    public List<Placements> selectPlacementsByExample(PlacementsExample example) {
        List<Placements> list = getSqlMapClientTemplate().queryForList("PLACEMENTS.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Placements selectPlacementsByPrimaryKey(Long placementId) {
        Placements key = new Placements();
        key.setPlacementId(placementId);
        Placements record = (Placements) getSqlMapClientTemplate().queryForObject("PLACEMENTS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updatePlacementsByExampleSelective(Placements record, PlacementsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PLACEMENTS.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updatePlacementsByExample(Placements record, PlacementsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PLACEMENTS.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updatePlacementsByPrimaryKeySelective(Placements record) {
        int rows = getSqlMapClientTemplate().update("PLACEMENTS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public int updatePlacementsByPrimaryKey(Placements record) {
        int rows = getSqlMapClientTemplate().update("PLACEMENTS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private static class UpdateByExampleParms extends PlacementsExample {
        private Object record;

        public UpdateByExampleParms(Object record, PlacementsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}