USE WEBTOOLS;

ALTER TABLE `STYLES`
MODIFY COLUMN `USER_NAME` varchar(255) NOT NULL;


ALTER TABLE `WIDGET`
MODIFY COLUMN `SITE_NAME` varchar(255) NOT NULL;


ALTER TABLE `STYLES`
MODIFY COLUMN `SITE_NAME` varchar(255) NOT NULL;
