USE WEBTOOLS;

ALTER TABLE `WIDGET`
ADD KEY `KEY_WIDGET_USERNAME` (`WIDGET_USERNAME`);

ALTER TABLE `WIDGET`
ADD KEY `KEY_WIDGET_SITENAME` (`SITE_NAME`);

ALTER TABLE `WIDGET`
MODIFY COLUMN `WIDGET_USERNAME` varchar(255) NOT NULL;

ALTER TABLE `WIDGET`
MODIFY COLUMN `WIDGET_PASSWORD` varchar(255) NOT NULL;

ALTER TABLE `WIDGET`
ADD KEY `WIDGET_STYLE_IDX` (`STYLE_ID`);




ALTER TABLE `STYLES`
ADD KEY `IDX_STYLES_SITENAME` (`SITE_NAME`);
