START TRANSACTION;

UPDATE `STYLES`
SET `SITE_NAME` = substring_index(USER_NAME, '@', -1)
WHERE SITE_NAME IS NULL AND USER_NAME IS NOT NULL;

UPDATE `WIDGET`
SET `SITE_NAME` = substring_index(WIDGET_USERNAME, '@', -1)
WHERE SITE_NAME IS NULL AND WIDGET_USERNAME IS NOT NULL;


COMMIT;