CREATE TABLE SITE (
  SITE_NAME VARCHAR(255),
  ORANGE_LEAP_USER_ID VARCHAR(255),
  ORANGE_LEAP_PASSWORD VARCHAR(255),
  PRIMARY KEY (SITE_NAME));

START TRANSACTION;

INSERT SITE
(SITE_NAME, ORANGE_LEAP_USER_ID, ORANGE_LEAP_PASSWORD)
SELECT DISTINCT SITE_NAME, WIDGET_USERNAME,
(SELECT WIDGET_PASSWORD FROM WIDGET C WHERE C.WIDGET_USERNAME = WIDGET.WIDGET_USERNAME ORDER BY C.WIDGET_CREATE_DATE DESC LIMIT 1)
FROM WIDGET
WHERE WIDGET_USERNAME =
(SELECT WIDGET_USERNAME FROM WIDGET B WHERE B.SITE_NAME = WIDGET.SITE_NAME
ORDER BY B.WIDGET_CREATE_DATE DESC LIMIT 1)
AND NOT EXISTS (SELECT * FROM SITE WHERE SITE.SITE_NAME = WIDGET.SITE_NAME);

COMMIT;

ALTER TABLE WIDGET drop column WIDGET_PASSWORD