package com.orangeleap.donatenow.domain;

import java.io.Serializable;

public class CustomEntityWidget implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CUSTOM_ENTITY_WIDGET.CUSTOM_ENTITY_WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private Long customEntityWidgetId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CUSTOM_ENTITY_WIDGET.CUSTOM_ENTITY_NAME
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private String customEntityName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table CUSTOM_ENTITY_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CUSTOM_ENTITY_WIDGET.CUSTOM_ENTITY_WIDGET_ID
     *
     * @return the value of CUSTOM_ENTITY_WIDGET.CUSTOM_ENTITY_WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Long getCustomEntityWidgetId() {
        return customEntityWidgetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CUSTOM_ENTITY_WIDGET.CUSTOM_ENTITY_WIDGET_ID
     *
     * @param customEntityWidgetId the value for CUSTOM_ENTITY_WIDGET.CUSTOM_ENTITY_WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setCustomEntityWidgetId(Long customEntityWidgetId) {
        this.customEntityWidgetId = customEntityWidgetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CUSTOM_ENTITY_WIDGET.CUSTOM_ENTITY_NAME
     *
     * @return the value of CUSTOM_ENTITY_WIDGET.CUSTOM_ENTITY_NAME
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public String getCustomEntityName() {
        return customEntityName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CUSTOM_ENTITY_WIDGET.CUSTOM_ENTITY_NAME
     *
     * @param customEntityName the value for CUSTOM_ENTITY_WIDGET.CUSTOM_ENTITY_NAME
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setCustomEntityName(String customEntityName) {
        this.customEntityName = customEntityName == null ? null : customEntityName.trim();
    }
}