package com.orangeleap.donatenow.domain;

import java.io.Serializable;
import java.util.List;
import com.orangeleap.client.PicklistItem;

public class DonationWidget extends Widget implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DONATION_WIDGET.DONATION_WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private Long donationWidgetId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DONATION_WIDGET.DONATION_WINDOW_MOTIVATION_CODE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private String donationWindowMotivationCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DONATION_WIDGET.DONATION_WIDGET_PROJECT_CODE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private String donationWidgetProjectCode;

  private List<PicklistItem> projectCodeList;
  private List<PicklistItem> motivationCodeList;

  public void setProjectCodeList(List<PicklistItem> items) { projectCodeList = items; }
  public void setMotivationCodeList(List<PicklistItem> items) { motivationCodeList = items; }
  public List<PicklistItem> getMotivationCodeList() { return motivationCodeList; }
  public List<PicklistItem> getProjectCodeList() { return projectCodeList; }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table DONATION_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DONATION_WIDGET.DONATION_WIDGET_ID
     *
     * @return the value of DONATION_WIDGET.DONATION_WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Long getDonationWidgetId() {
        return donationWidgetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DONATION_WIDGET.DONATION_WIDGET_ID
     *
     * @param donationWidgetId the value for DONATION_WIDGET.DONATION_WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setDonationWidgetId(Long donationWidgetId) {
        this.donationWidgetId = donationWidgetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DONATION_WIDGET.DONATION_WINDOW_MOTIVATION_CODE
     *
     * @return the value of DONATION_WIDGET.DONATION_WINDOW_MOTIVATION_CODE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public String getDonationWindowMotivationCode() {
        return donationWindowMotivationCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DONATION_WIDGET.DONATION_WINDOW_MOTIVATION_CODE
     *
     * @param donationWindowMotivationCode the value for DONATION_WIDGET.DONATION_WINDOW_MOTIVATION_CODE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setDonationWindowMotivationCode(String donationWindowMotivationCode) {
        this.donationWindowMotivationCode = donationWindowMotivationCode == null ? null : donationWindowMotivationCode.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DONATION_WIDGET.DONATION_WIDGET_PROJECT_CODE
     *
     * @return the value of DONATION_WIDGET.DONATION_WIDGET_PROJECT_CODE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public String getDonationWidgetProjectCode() {
        return donationWidgetProjectCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DONATION_WIDGET.DONATION_WIDGET_PROJECT_CODE
     *
     * @param donationWidgetProjectCode the value for DONATION_WIDGET.DONATION_WIDGET_PROJECT_CODE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setDonationWidgetProjectCode(String donationWidgetProjectCode) {
        this.donationWidgetProjectCode = donationWidgetProjectCode == null ? null : donationWidgetProjectCode.trim();
    }
}