package com.orangeleap.donatenow.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LoginWidgetExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public LoginWidgetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    protected LoginWidgetExample(LoginWidgetExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table LOGIN_WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andLoginWidgetIdIsNull() {
            addCriterion("LOGIN_WIDGET_ID is null");
            return this;
        }

        public Criteria andLoginWidgetIdIsNotNull() {
            addCriterion("LOGIN_WIDGET_ID is not null");
            return this;
        }

        public Criteria andLoginWidgetIdEqualTo(Long value) {
            addCriterion("LOGIN_WIDGET_ID =", value, "loginWidgetId");
            return this;
        }

        public Criteria andLoginWidgetIdNotEqualTo(Long value) {
            addCriterion("LOGIN_WIDGET_ID <>", value, "loginWidgetId");
            return this;
        }

        public Criteria andLoginWidgetIdGreaterThan(Long value) {
            addCriterion("LOGIN_WIDGET_ID >", value, "loginWidgetId");
            return this;
        }

        public Criteria andLoginWidgetIdGreaterThanOrEqualTo(Long value) {
            addCriterion("LOGIN_WIDGET_ID >=", value, "loginWidgetId");
            return this;
        }

        public Criteria andLoginWidgetIdLessThan(Long value) {
            addCriterion("LOGIN_WIDGET_ID <", value, "loginWidgetId");
            return this;
        }

        public Criteria andLoginWidgetIdLessThanOrEqualTo(Long value) {
            addCriterion("LOGIN_WIDGET_ID <=", value, "loginWidgetId");
            return this;
        }

        public Criteria andLoginWidgetIdIn(List<Long> values) {
            addCriterion("LOGIN_WIDGET_ID in", values, "loginWidgetId");
            return this;
        }

        public Criteria andLoginWidgetIdNotIn(List<Long> values) {
            addCriterion("LOGIN_WIDGET_ID not in", values, "loginWidgetId");
            return this;
        }

        public Criteria andLoginWidgetIdBetween(Long value1, Long value2) {
            addCriterion("LOGIN_WIDGET_ID between", value1, value2, "loginWidgetId");
            return this;
        }

        public Criteria andLoginWidgetIdNotBetween(Long value1, Long value2) {
            addCriterion("LOGIN_WIDGET_ID not between", value1, value2, "loginWidgetId");
            return this;
        }

        public Criteria andLoginWidgetLastLoginDateIsNull() {
            addCriterion("LOGIN_WIDGET_LAST_LOGIN_DATE is null");
            return this;
        }

        public Criteria andLoginWidgetLastLoginDateIsNotNull() {
            addCriterion("LOGIN_WIDGET_LAST_LOGIN_DATE is not null");
            return this;
        }

        public Criteria andLoginWidgetLastLoginDateEqualTo(Date value) {
            addCriterion("LOGIN_WIDGET_LAST_LOGIN_DATE =", value, "loginWidgetLastLoginDate");
            return this;
        }

        public Criteria andLoginWidgetLastLoginDateNotEqualTo(Date value) {
            addCriterion("LOGIN_WIDGET_LAST_LOGIN_DATE <>", value, "loginWidgetLastLoginDate");
            return this;
        }

        public Criteria andLoginWidgetLastLoginDateGreaterThan(Date value) {
            addCriterion("LOGIN_WIDGET_LAST_LOGIN_DATE >", value, "loginWidgetLastLoginDate");
            return this;
        }

        public Criteria andLoginWidgetLastLoginDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LOGIN_WIDGET_LAST_LOGIN_DATE >=", value, "loginWidgetLastLoginDate");
            return this;
        }

        public Criteria andLoginWidgetLastLoginDateLessThan(Date value) {
            addCriterion("LOGIN_WIDGET_LAST_LOGIN_DATE <", value, "loginWidgetLastLoginDate");
            return this;
        }

        public Criteria andLoginWidgetLastLoginDateLessThanOrEqualTo(Date value) {
            addCriterion("LOGIN_WIDGET_LAST_LOGIN_DATE <=", value, "loginWidgetLastLoginDate");
            return this;
        }

        public Criteria andLoginWidgetLastLoginDateIn(List<Date> values) {
            addCriterion("LOGIN_WIDGET_LAST_LOGIN_DATE in", values, "loginWidgetLastLoginDate");
            return this;
        }

        public Criteria andLoginWidgetLastLoginDateNotIn(List<Date> values) {
            addCriterion("LOGIN_WIDGET_LAST_LOGIN_DATE not in", values, "loginWidgetLastLoginDate");
            return this;
        }

        public Criteria andLoginWidgetLastLoginDateBetween(Date value1, Date value2) {
            addCriterion("LOGIN_WIDGET_LAST_LOGIN_DATE between", value1, value2, "loginWidgetLastLoginDate");
            return this;
        }

        public Criteria andLoginWidgetLastLoginDateNotBetween(Date value1, Date value2) {
            addCriterion("LOGIN_WIDGET_LAST_LOGIN_DATE not between", value1, value2, "loginWidgetLastLoginDate");
            return this;
        }
    }
}