package com.orangeleap.donatenow.domain;

import java.io.Serializable;

public class Placements implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PLACEMENTS.PLACEMENT_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private Long placementId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PLACEMENTS.WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private Long widgetId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PLACEMENTS.PLACEMENT_URL
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private String placementUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PLACEMENTS.ERROR_COUNT
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private Long errorCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PLACEMENTS.VIEW_COUNT
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private Long viewCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table PLACEMENTS
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PLACEMENTS.PLACEMENT_ID
     *
     * @return the value of PLACEMENTS.PLACEMENT_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Long getPlacementId() {
        return placementId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PLACEMENTS.PLACEMENT_ID
     *
     * @param placementId the value for PLACEMENTS.PLACEMENT_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setPlacementId(Long placementId) {
        this.placementId = placementId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PLACEMENTS.WIDGET_ID
     *
     * @return the value of PLACEMENTS.WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Long getWidgetId() {
        return widgetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PLACEMENTS.WIDGET_ID
     *
     * @param widgetId the value for PLACEMENTS.WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setWidgetId(Long widgetId) {
        this.widgetId = widgetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PLACEMENTS.PLACEMENT_URL
     *
     * @return the value of PLACEMENTS.PLACEMENT_URL
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public String getPlacementUrl() {
        return placementUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PLACEMENTS.PLACEMENT_URL
     *
     * @param placementUrl the value for PLACEMENTS.PLACEMENT_URL
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setPlacementUrl(String placementUrl) {
        this.placementUrl = placementUrl == null ? null : placementUrl.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PLACEMENTS.ERROR_COUNT
     *
     * @return the value of PLACEMENTS.ERROR_COUNT
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Long getErrorCount() {
        return errorCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PLACEMENTS.ERROR_COUNT
     *
     * @param errorCount the value for PLACEMENTS.ERROR_COUNT
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setErrorCount(Long errorCount) {
        this.errorCount = errorCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PLACEMENTS.VIEW_COUNT
     *
     * @return the value of PLACEMENTS.VIEW_COUNT
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PLACEMENTS.VIEW_COUNT
     *
     * @param viewCount the value for PLACEMENTS.VIEW_COUNT
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }
}