package com.orangeleap.donatenow.domain;

import java.io.Serializable;
import java.util.Date;

public class Widget implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WIDGET.WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private Long widgetId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WIDGET.WIDGET_GUID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private String widgetGuid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WIDGET.WIDGET_USERNAME
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private String widgetUsername;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WIDGET.WIDGET_PASSWORD
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private String widgetPassword;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WIDGET.WIDGET_ERROR_COUNT
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private Long widgetErrorCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WIDGET.WIDGET_CREATE_DATE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private Date widgetCreateDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WIDGET.WIDGET_HTML
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private String widgetHtml;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WIDGET.WIDGET_VIEW_COUNT
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private Long widgetViewCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WIDGET.WIDGET_TYPE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private String widgetType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table WIDGET
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WIDGET.WIDGET_ID
     *
     * @return the value of WIDGET.WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Long getWidgetId() {
        return widgetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WIDGET.WIDGET_ID
     *
     * @param widgetId the value for WIDGET.WIDGET_ID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setWidgetId(Long widgetId) {
        this.widgetId = widgetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WIDGET.WIDGET_GUID
     *
     * @return the value of WIDGET.WIDGET_GUID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public String getWidgetGuid() {
        return widgetGuid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WIDGET.WIDGET_GUID
     *
     * @param widgetGuid the value for WIDGET.WIDGET_GUID
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setWidgetGuid(String widgetGuid) {
        this.widgetGuid = widgetGuid == null ? null : widgetGuid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WIDGET.WIDGET_USERNAME
     *
     * @return the value of WIDGET.WIDGET_USERNAME
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public String getWidgetUsername() {
        return widgetUsername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WIDGET.WIDGET_USERNAME
     *
     * @param widgetUsername the value for WIDGET.WIDGET_USERNAME
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setWidgetUsername(String widgetUsername) {
        this.widgetUsername = widgetUsername == null ? null : widgetUsername.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WIDGET.WIDGET_PASSWORD
     *
     * @return the value of WIDGET.WIDGET_PASSWORD
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public String getWidgetPassword() {
        return widgetPassword;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WIDGET.WIDGET_PASSWORD
     *
     * @param widgetPassword the value for WIDGET.WIDGET_PASSWORD
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setWidgetPassword(String widgetPassword) {
        this.widgetPassword = widgetPassword == null ? null : widgetPassword.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WIDGET.WIDGET_ERROR_COUNT
     *
     * @return the value of WIDGET.WIDGET_ERROR_COUNT
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Long getWidgetErrorCount() {
        return widgetErrorCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WIDGET.WIDGET_ERROR_COUNT
     *
     * @param widgetErrorCount the value for WIDGET.WIDGET_ERROR_COUNT
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setWidgetErrorCount(Long widgetErrorCount) {
        this.widgetErrorCount = widgetErrorCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WIDGET.WIDGET_CREATE_DATE
     *
     * @return the value of WIDGET.WIDGET_CREATE_DATE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Date getWidgetCreateDate() {
        return widgetCreateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WIDGET.WIDGET_CREATE_DATE
     *
     * @param widgetCreateDate the value for WIDGET.WIDGET_CREATE_DATE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setWidgetCreateDate(Date widgetCreateDate) {
        this.widgetCreateDate = widgetCreateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WIDGET.WIDGET_HTML
     *
     * @return the value of WIDGET.WIDGET_HTML
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public String getWidgetHtml() {
        return widgetHtml;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WIDGET.WIDGET_HTML
     *
     * @param widgetHtml the value for WIDGET.WIDGET_HTML
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setWidgetHtml(String widgetHtml) {
        this.widgetHtml = widgetHtml == null ? null : widgetHtml.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WIDGET.WIDGET_VIEW_COUNT
     *
     * @return the value of WIDGET.WIDGET_VIEW_COUNT
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public Long getWidgetViewCount() {
        return widgetViewCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WIDGET.WIDGET_VIEW_COUNT
     *
     * @param widgetViewCount the value for WIDGET.WIDGET_VIEW_COUNT
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setWidgetViewCount(Long widgetViewCount) {
        this.widgetViewCount = widgetViewCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WIDGET.WIDGET_TYPE
     *
     * @return the value of WIDGET.WIDGET_TYPE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public String getWidgetType() {
        return widgetType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WIDGET.WIDGET_TYPE
     *
     * @param widgetType the value for WIDGET.WIDGET_TYPE
     *
     * @ibatorgenerated Tue Jun 08 15:31:29 CDT 2010
     */
    public void setWidgetType(String widgetType) {
        this.widgetType = widgetType == null ? null : widgetType.trim();
    }
}